#!/usr/bin/env bash
#Update and Install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    server_name localhost;
    root /etc/nginx/html;
    index index.html;
    location / {
        root /etc/nginx/html;
        index index.html;
    }
    location /redirect_me {
        return 301  https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart