#!/usr/bin/env bash
#fizzbuzz
for (( n=1; n < 101; n++))
do
	if (( n % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( n % 5 == 0 )); then
		echo "Buzz"
	elif (( n % 3 == 0 )); then
		echo "Fizz"
	else echo "$n"
	fi
done
