#!/usr/bin/env bash
#configuring all dis stuff i guess
Host 5591-web-01
    HostName 15.236.141.45
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

Host 5591-web-02
    HostName 15.188.238.187
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

Host 5591-lb-01
    HostName 13.37.237.76
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no