#!/usr/bin/env bash
#Transfers a file from our client to a server

#!/usr/bin/env bash
# Transfer a file to a remote host
if (( $# !=4 )); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
exit 0
