#!/usr/bin/env bash
#Update and Install haproxy web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install haproxy -y

#config
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 5591-web-01 15.236.141.45:80 check
    server 5591-web-02 15.188.238.187:80 check
EOF

#restart haproxy
sudo service haproxy restart