#!/usr/bin/env bash
#Update and Install nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install haproxy -y

#config
sudo sed -i 's/^\(ENABLED=\).*/\1true/' /etc/default/haproxy
sudo cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 5591-web-01 15.236.141.45 check
    server 5591-web-02 15.188.238.187 check
EOF

#restart haproxy
sudo service haproxy restart
sudo update-rc.d haproxy defaults